-- keyUpDown = function(modifiers, key)
-- 	hs.eventtap.keyStroke(modifiers, key, 0)
-- end
-- require("control-escape")
-- hs.notify.new({ title = "Hammerspoon", informativeText = "Damn Right Whore!! sike nah loaded.." }):send()
